<?php

namespace think\worker\concerns;

use RuntimeException;
use think\App;
use think\worker\Ipc;
use think\worker\Watcher;
use think\worker\Worker;
use Workerman\Redis\Client;
use Workerman\Timer;

/**
 * Trait InteractsWithServer
 * @property App $container
 */
trait InteractsWithServer
{
    /** @var Ipc */
    protected $ipc;

    protected $workerId = null;
    protected $stopping = false;

    public function addWorker(callable $func, $name = 'none', int $count = 1, ?string $socket = null, array $socketContext = []): Worker
    {
        $worker = $socket ? new Worker($socket, $socketContext) : new Worker();

        $worker->name  = $name;
        $worker->count = $count;

        $worker->onWorkerStart = function (Worker $worker) use ($func) {
            $this->clearCache();
            $this->prepareApplication();

            $this->conduit->connect();

            $this->workerId = $this->ipc->listenMessage();

            $this->triggerEvent('workerStart', $worker);

            // Windows 下热更新：reloadable worker 轮询重载标记，命中则退出交由 master 重启
            if (DIRECTORY_SEPARATOR !== '/' && $this->getConfig('hot_update.enable', false)) {
                $this->watchWinReload();
            }

            $func($worker);
        };

        $worker->onWorkerReload = function () {
            $this->stopping = true;
        };

        return $worker;
    }

    public function getWorkerId()
    {
        return $this->workerId;
    }

    public function isStopping()
    {
        return $this->stopping;
    }

    /**
     * 启动服务
     */
    public function start(): void
    {
        if (DIRECTORY_SEPARATOR === '/') {
            $this->startLinux();
        } else {
            $this->startWindows();
        }
    }

    /**
     * Linux 下启动：单文件多 worker + fork。
     */
    protected function startLinux(): void
    {
        $this->initialize();
        $this->prepareIpc();
        $this->triggerEvent('init');

        //热更新
        if ($this->getConfig('hot_update.enable', false)) {
            $this->addHotUpdateWorker();
        }

        Worker::runAll();
    }

    /**
     * Windows 下启动：为每个 worker 生成独立启动文件并以多进程方式拉起，由 Workerman master 监控。
     */
    protected function startWindows(): void
    {
        $files = $this->createWindowsStartFiles();

        $this->launchWindows($files);
    }

    protected function createWindowsStartFiles(): array
    {
        $root   = $this->container->getRootPath();
        $winDir = $root . 'runtime' . DIRECTORY_SEPARATOR . 'win' . DIRECTORY_SEPARATOR;

        if (!is_dir($winDir)) {
            mkdir($winDir, 0777, true);
        }

        $files = [];

        foreach ($this->workerTypes() as $type) {
            $safeType = str_replace([':', '\\', '/', '*', '?', '"', '<', '>', '|'], '_', $type);
            $file     = $winDir . 'start_' . $safeType . '.php';

            file_put_contents($file, $this->buildWindowsStartFile($root, $type));

            $files[] = $file;
        }

        return $files;
    }

    protected function buildWindowsStartFile(string $root, string $type): string
    {
        $rootLiteral = var_export(rtrim($root, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR, true);
        $typeLiteral = var_export($type, true);

        return <<<PHP
<?php
// auto-generated by think-worker, do not edit
chdir(__DIR__ . '/../../');

// 沿目录向上查找 vendor/autoload.php
\$autoload = __DIR__ . '/../../vendor/autoload.php';
if (!is_file(\$autoload)) {
    \$dir = dirname(__DIR__);
    while (\$dir !== dirname(\$dir)) {
        \$candidate = \$dir . '/vendor/autoload.php';
        if (is_file(\$candidate)) {
            \$autoload = \$candidate;
            break;
        }
        \$dir = dirname(\$dir);
    }
}
require \$autoload;

\$app = new \\think\\App({$rootLiteral});
\$app->initialize();

\$manager = new \\think\\worker\\Manager(\$app);
\$manager->prepareWorker({$typeLiteral});

\\think\\worker\\Worker::runAll();
PHP;
    }

    protected function launchWindows(array $files): void
    {
        $command = array_merge([PHP_BINARY], $files);

        $descriptorSpec = [STDIN, STDOUT, STDOUT];
        $process        = proc_open($command, $descriptorSpec, $pipes);

        if (!is_resource($process)) {
            throw new RuntimeException('Failed to start worker processes');
        }

        $exitCode = proc_close($process);

        exit($exitCode);
    }

    protected function prepareIpc()
    {
        $this->ipc = $this->container->make(Ipc::class);
    }

    public function sendMessage($workerId, $message)
    {
        $this->ipc->sendMessage($workerId, $message);
    }

    /**
     * 热更新
     */
    protected function addHotUpdateWorker()
    {
        $worker = new Worker();

        $worker->name       = 'hot update';
        $worker->reloadable = false;

        $worker->onWorkerStart = function () {
            $watcher = $this->container->make(Watcher::class);
            $watcher->watch(function () {
                if (DIRECTORY_SEPARATOR === '/') {
                    posix_kill(posix_getppid(), SIGUSR1);
                } else {
                    $this->sendWinReload();
                }
            });
        };
    }

    /**
     * Windows 下写入重载标记，reloadable worker 轮询到后退出由 master 重启。
     */
    protected function sendWinReload()
    {
        file_put_contents($this->winReloadFlag(), time());
    }

    protected function watchWinReload()
    {
        $flag = $this->winReloadFlag();

        Timer::add(1, function () use ($flag) {
            if (is_file($flag)) {
                @unlink($flag);
                Worker::stopAll(0, 'reload');
            }
        });
    }

    protected function winReloadFlag()
    {
        return runtime_path() . 'win' . DIRECTORY_SEPARATOR . 'reload.flag';
    }

    /**
     * 清除apc、op缓存
     */
    protected function clearCache()
    {
        if (extension_loaded('apc')) {
            apc_clear_cache();
        }

        if (extension_loaded('Zend OPcache')) {
            opcache_reset();
        }
    }

}